#!/bin/sh

mysql -u root -e "SET GLOBAL host_cache_size=0"

mysql -u root -e "SET SQL_LOG_BIN=0;
					CREATE USER ${MYSQL_REPLICA_USER}@'%' IDENTIFIED BY '${MYSQL_REPLICA_USER_PASSWORD}' REQUIRE SSL;
					GRANT REPLICATION SLAVE ON *.* TO ${MYSQL_REPLICA_USER}@'%';
					GRANT CONNECTION_ADMIN ON *.* TO ${MYSQL_REPLICA_USER}@'%';
					GRANT BACKUP_ADMIN ON *.* TO ${MYSQL_REPLICA_USER}@'%';
					GRANT GROUP_REPLICATION_STREAM ON *.* TO ${MYSQL_REPLICA_USER}@'%';
					FLUSH PRIVILEGES;
					SET SQL_LOG_BIN=1;
					"